# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: "#home"
    weight: 10
  - name: About
    url: "#about"
    weight: 20
  - name: Projects
    url: "#projects"
    weight: 25
  - name: 📚 Guides & Resources
    url: "#guides"
    weight: 30
  - name: 🙋 Community & Network
    url: "#community"
    weight: 30
  - name: 📝 Blog
    url: "#blog"
    weight: 40
  - name: 💚 Members
    url: "#members"
    weight: 50
  - name: 🤝 Associates
    url: "#associates"
    weight: 60
  - name: 👋 Join
    url: "#join"
    weight: 70
  - name: 💬 Q&A
    url: "#faq"
    weight: 80
